// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoLocadoraRepository.Features.Filmes;

namespace VideoLocadoraRepository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VideoLocadora.Domain.Features.Filmes.Filme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ativo")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Filmes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = 1,
                            DataCriacao = new DateTime(2021, 5, 30, 18, 25, 31, 24, DateTimeKind.Local).AddTicks(3118),
                            Genero = "Terror",
                            Nome = "Filme1"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = 1,
                            DataCriacao = new DateTime(2021, 5, 30, 18, 25, 31, 25, DateTimeKind.Local).AddTicks(5303),
                            Genero = "Comedia",
                            Nome = "Filme2"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = 0,
                            DataCriacao = new DateTime(2021, 5, 30, 18, 25, 31, 25, DateTimeKind.Local).AddTicks(5321),
                            Genero = "Aventura",
                            Nome = "Filme3"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = 0,
                            DataCriacao = new DateTime(2021, 5, 30, 18, 25, 31, 25, DateTimeKind.Local).AddTicks(5323),
                            Genero = "Ficcao",
                            Nome = "Filme4"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = 1,
                            DataCriacao = new DateTime(2021, 5, 30, 18, 25, 31, 25, DateTimeKind.Local).AddTicks(5325),
                            Genero = "Romance",
                            Nome = "Filme5"
                        });
                });

            modelBuilder.Entity("VideoLocadora.Domain.Features.Generos.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ativo")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = 1,
                            DataCriacao = new DateTime(2021, 5, 30, 18, 25, 31, 26, DateTimeKind.Local).AddTicks(8794),
                            Nome = "Terror"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = 1,
                            DataCriacao = new DateTime(2021, 5, 30, 18, 25, 31, 26, DateTimeKind.Local).AddTicks(9502),
                            Nome = "Comedia"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = 0,
                            DataCriacao = new DateTime(2021, 5, 30, 18, 25, 31, 26, DateTimeKind.Local).AddTicks(9508),
                            Nome = "Aventura"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = 0,
                            DataCriacao = new DateTime(2021, 5, 30, 18, 25, 31, 26, DateTimeKind.Local).AddTicks(9510),
                            Nome = "Ficcao"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = 1,
                            DataCriacao = new DateTime(2021, 5, 30, 18, 25, 31, 26, DateTimeKind.Local).AddTicks(9512),
                            Nome = "Romance"
                        });
                });

            modelBuilder.Entity("VideoLocadora.Domain.Features.Locacoes.Locacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPFCliente")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("DataLocacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ListaFilmes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locacoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CPFCliente = "69874521830",
                            DataLocacao = new DateTime(2021, 5, 30, 18, 25, 31, 27, DateTimeKind.Local).AddTicks(1003),
                            ListaFilmes = "Filme 1, Filme 2, Filme 3"
                        },
                        new
                        {
                            Id = 2,
                            CPFCliente = "12457865420",
                            DataLocacao = new DateTime(2021, 5, 30, 18, 25, 31, 27, DateTimeKind.Local).AddTicks(1359),
                            ListaFilmes = "Filme 1"
                        },
                        new
                        {
                            Id = 3,
                            CPFCliente = "98563258741",
                            DataLocacao = new DateTime(2021, 5, 30, 18, 25, 31, 27, DateTimeKind.Local).AddTicks(1364),
                            ListaFilmes = "Filme 2, Filme 3"
                        },
                        new
                        {
                            Id = 4,
                            CPFCliente = "98633365792",
                            DataLocacao = new DateTime(2021, 5, 30, 18, 25, 31, 27, DateTimeKind.Local).AddTicks(1366),
                            ListaFilmes = "Filme 3"
                        },
                        new
                        {
                            Id = 5,
                            CPFCliente = "11478569831",
                            DataLocacao = new DateTime(2021, 5, 30, 18, 25, 31, 27, DateTimeKind.Local).AddTicks(1367),
                            ListaFilmes = "Filme 5, Filme 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
